// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC8vIZlqIiJZ0OuSHbv0s08QWBq9aV-q4',
    appId: '1:857780274855:web:7f01d593502aeab9d5bd82',
    messagingSenderId: '857780274855',
    projectId: 'todo-a4b80',
    authDomain: 'todo-a4b80.firebaseapp.com',
    storageBucket: 'todo-a4b80.firebasestorage.app',
    measurementId: 'G-77HTSZ1TSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7MYTnOajYxi0T8Qtri-_MBNa_TrVwlpg',
    appId: '1:857780274855:android:c1be14ceeb6c1325d5bd82',
    messagingSenderId: '857780274855',
    projectId: 'todo-a4b80',
    storageBucket: 'todo-a4b80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq2aHTQ4tYIJwy6at00av4PhdLKU2riOY',
    appId: '1:857780274855:ios:6b94c84e905383c9d5bd82',
    messagingSenderId: '857780274855',
    projectId: 'todo-a4b80',
    storageBucket: 'todo-a4b80.firebasestorage.app',
    iosBundleId: 'com.example.tally',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq2aHTQ4tYIJwy6at00av4PhdLKU2riOY',
    appId: '1:857780274855:ios:6b94c84e905383c9d5bd82',
    messagingSenderId: '857780274855',
    projectId: 'todo-a4b80',
    storageBucket: 'todo-a4b80.firebasestorage.app',
    iosBundleId: 'com.example.tally',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC8vIZlqIiJZ0OuSHbv0s08QWBq9aV-q4',
    appId: '1:857780274855:web:544e0162827fb712d5bd82',
    messagingSenderId: '857780274855',
    projectId: 'todo-a4b80',
    authDomain: 'todo-a4b80.firebaseapp.com',
    storageBucket: 'todo-a4b80.firebasestorage.app',
    measurementId: 'G-WPP675NV79',
  );
}
